FROM node:latest
MAINTAINER Dwsy

RUN mkdir -p /root/nestServer
WORKDIR /root/nestServer
COPY . /root/nestServer

RUN yarn config set registry https://registry.npm.taobao.org &&\
    npm i -g @nestjs/cli@7.5.1 &&\
    yarn && nest bulid admin &&\
    node dist\\apps\\admin\\main.js
EXPOSE 3000

CMD ["node", "dist\\apps\\admin\\main.js"]
CMD ["start"]