FROM node:alpine
ENV DB=mongodb://127.0.0.1:27017/myblog
ENV ADMIN_PORT=3000
ENV SECRET=qwe123123123
COPY . /home/server
RUN cd /home/server && npm config set registry https://registry.npm.taobao.org && npm i -g @nestjs/cli@7.5.1 && yarn config set registry https://registry.npm.taobao.org -g &&yarn global add pm2 && yarn&& nest build admin
WORKDIR /home/server
EXPOSE 3000
CMD [ "node","dist/apps/admin/main.js" ]